// Auto-generated by scripts/generate_domains.py — do not edit by hand.
// Source: cloudflare-radar_top-100-domains_20260315.csv
const TOP_DOMAINS = [
  {
    "domain": "google.com",
    "sld": "google"
  },
  {
    "domain": "googleapis.com",
    "sld": "googleapis"
  },
  {
    "domain": "gstatic.com",
    "sld": "gstatic"
  },
  {
    "domain": "cloudflare.com",
    "sld": "cloudflare"
  },
  {
    "domain": "apple.com",
    "sld": "apple"
  },
  {
    "domain": "microsoft.com",
    "sld": "microsoft"
  },
  {
    "domain": "facebook.com",
    "sld": "facebook"
  },
  {
    "domain": "amazonaws.com",
    "sld": "amazonaws"
  },
  {
    "domain": "googlevideo.com",
    "sld": "googlevideo"
  },
  {
    "domain": "amazon.com",
    "sld": "amazon"
  },
  {
    "domain": "fbcdn.net",
    "sld": "fbcdn"
  },
  {
    "domain": "chatgpt.com",
    "sld": "chatgpt"
  },
  {
    "domain": "whatsapp.net",
    "sld": "whatsapp"
  },
  {
    "domain": "instagram.com",
    "sld": "instagram"
  },
  {
    "domain": "youtube.com",
    "sld": "youtube"
  },
  {
    "domain": "doubleclick.net",
    "sld": "doubleclick"
  },
  {
    "domain": "netflix.com",
    "sld": "netflix"
  },
  {
    "domain": "akadns.net",
    "sld": "akadns"
  },
  {
    "domain": "ntp.org",
    "sld": "ntp"
  },
  {
    "domain": "apple-dns.net",
    "sld": "apple-dns"
  },
  {
    "domain": "googleusercontent.com",
    "sld": "googleusercontent"
  },
  {
    "domain": "bing.com",
    "sld": "bing"
  },
  {
    "domain": "googlesyndication.com",
    "sld": "googlesyndication"
  },
  {
    "domain": "icloud.com",
    "sld": "icloud"
  },
  {
    "domain": "tiktokcdn.com",
    "sld": "tiktokcdn"
  },
  {
    "domain": "akamai.net",
    "sld": "akamai"
  },
  {
    "domain": "live.com",
    "sld": "live"
  },
  {
    "domain": "tiktokv.com",
    "sld": "tiktokv"
  },
  {
    "domain": "cloudfront.net",
    "sld": "cloudfront"
  },
  {
    "domain": "cloudflare-dns.com",
    "sld": "cloudflare-dns"
  },
  {
    "domain": "aaplimg.com",
    "sld": "aaplimg"
  },
  {
    "domain": "ytimg.com",
    "sld": "ytimg"
  },
  {
    "domain": "ui.com",
    "sld": "ui"
  },
  {
    "domain": "yahoo.com",
    "sld": "yahoo"
  },
  {
    "domain": "akamaiedge.net",
    "sld": "akamaiedge"
  },
  {
    "domain": "gvt2.com",
    "sld": "gvt2"
  },
  {
    "domain": "spotify.com",
    "sld": "spotify"
  },
  {
    "domain": "wikipedia.org",
    "sld": "wikipedia"
  },
  {
    "domain": "gvt1.com",
    "sld": "gvt1"
  },
  {
    "domain": "fastly.net",
    "sld": "fastly"
  },
  {
    "domain": "cdninstagram.com",
    "sld": "cdninstagram"
  },
  {
    "domain": "office.com",
    "sld": "office"
  },
  {
    "domain": "samsung.com",
    "sld": "samsung"
  },
  {
    "domain": "dns.google",
    "sld": "dns"
  },
  {
    "domain": "roblox.com",
    "sld": "roblox"
  },
  {
    "domain": "baidu.com",
    "sld": "baidu"
  },
  {
    "domain": "criteo.com",
    "sld": "criteo"
  },
  {
    "domain": "one.one",
    "sld": "one"
  },
  {
    "domain": "steamserver.net",
    "sld": "steamserver"
  },
  {
    "domain": "app-measurement.com",
    "sld": "app-measurement"
  },
  {
    "domain": "google-analytics.com",
    "sld": "google-analytics"
  },
  {
    "domain": "app-analytics-services.com",
    "sld": "app-analytics-services"
  },
  {
    "domain": "sentry.io",
    "sld": "sentry"
  },
  {
    "domain": "microsoftonline.com",
    "sld": "microsoftonline"
  },
  {
    "domain": "appsflyersdk.com",
    "sld": "appsflyersdk"
  },
  {
    "domain": "googleadservices.com",
    "sld": "googleadservices"
  },
  {
    "domain": "applovin.com",
    "sld": "applovin"
  },
  {
    "domain": "3gppnetwork.org",
    "sld": "3gppnetwork"
  },
  {
    "domain": "googletagmanager.com",
    "sld": "googletagmanager"
  },
  {
    "domain": "msftncsi.com",
    "sld": "msftncsi"
  },
  {
    "domain": "snapchat.com",
    "sld": "snapchat"
  },
  {
    "domain": "whatsapp.com",
    "sld": "whatsapp"
  },
  {
    "domain": "msn.com",
    "sld": "msn"
  },
  {
    "domain": "trafficmanager.net",
    "sld": "trafficmanager"
  },
  {
    "domain": "ggpht.com",
    "sld": "ggpht"
  },
  {
    "domain": "azure.com",
    "sld": "azure"
  },
  {
    "domain": "unity3d.com",
    "sld": "unity3d"
  },
  {
    "domain": "windows.com",
    "sld": "windows"
  },
  {
    "domain": "amazon-adsystem.com",
    "sld": "amazon-adsystem"
  },
  {
    "domain": "amazon.dev",
    "sld": "amazon"
  },
  {
    "domain": "windows.net",
    "sld": "windows"
  },
  {
    "domain": "a2z.com",
    "sld": "a2z"
  },
  {
    "domain": "linkedin.com",
    "sld": "linkedin"
  },
  {
    "domain": "xiaomi.com",
    "sld": "xiaomi"
  },
  {
    "domain": "tiktokcdn-us.com",
    "sld": "tiktokcdn-us"
  },
  {
    "domain": "playstation.net",
    "sld": "playstation"
  },
  {
    "domain": "0xrpc.io",
    "sld": "0xrpc"
  },
  {
    "domain": "skype.com",
    "sld": "skype"
  },
  {
    "domain": "avast.com",
    "sld": "avast"
  },
  {
    "domain": "msftconnecttest.com",
    "sld": "msftconnecttest"
  },
  {
    "domain": "vungle.com",
    "sld": "vungle"
  },
  {
    "domain": "taboola.com",
    "sld": "taboola"
  },
  {
    "domain": "windowsupdate.com",
    "sld": "windowsupdate"
  },
  {
    "domain": "aws.dev",
    "sld": "aws"
  },
  {
    "domain": "cdn-apple.com",
    "sld": "cdn-apple"
  },
  {
    "domain": "merkle.io",
    "sld": "merkle"
  },
  {
    "domain": "avsxappcaptiveportal.com",
    "sld": "avsxappcaptiveportal"
  },
  {
    "domain": "llamarpc.com",
    "sld": "llamarpc"
  },
  {
    "domain": "rubiconproject.com",
    "sld": "rubiconproject"
  },
  {
    "domain": "publicnode.com",
    "sld": "publicnode"
  },
  {
    "domain": "adtrafficquality.google",
    "sld": "adtrafficquality"
  },
  {
    "domain": "gmail.com",
    "sld": "gmail"
  },
  {
    "domain": "digicert.com",
    "sld": "digicert"
  },
  {
    "domain": "android.com",
    "sld": "android"
  },
  {
    "domain": "qq.com",
    "sld": "qq"
  },
  {
    "domain": "appsflyer.com",
    "sld": "appsflyer"
  },
  {
    "domain": "kwai-pro.com",
    "sld": "kwai-pro"
  },
  {
    "domain": "office.net",
    "sld": "office"
  },
  {
    "domain": "roku.com",
    "sld": "roku"
  },
  {
    "domain": "miui.com",
    "sld": "miui"
  }
];
