#!/usr/bin/env python3
"""
Generate extension/top-domains.js from the Cloudflare Radar top-100 CSV.

Usage:
    python scripts/generate_domains.py
"""

import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).parent.parent
CSV_PATH = ROOT / "cloudflare-radar_top-100-domains_20260315.csv"
OUT_PATH = ROOT / "extension" / "top-domains.js"


def extract_sld(domain: str) -> str:
    """
    Return the second-level domain (SLD) token — everything to the left of the
    final public suffix dot.  All 100 entries in the Cloudflare top-100 list
    use single-component TLDs (.com, .net, .org, .io, .google, etc.), so a
    simple rsplit on the last dot is correct for this dataset.

    Examples:
        apple.com       -> apple
        googleapis.com  -> googleapis
        cdn-apple.com   -> cdn-apple
        dns.google      -> dns
    """
    return domain.rsplit(".", 1)[0]


def main() -> None:
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            domain = row["domain"].strip().lower()
            sld = extract_sld(domain)
            rows.append({"domain": domain, "sld": sld})

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        "// Auto-generated by scripts/generate_domains.py — do not edit by hand.\n"
        "// Source: cloudflare-radar_top-100-domains_20260315.csv\n"
        "const TOP_DOMAINS = " + json.dumps(rows, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(rows)} entries to {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
